---
config:
  theme: mc
  layout: elk
  flowchart:
    curve: basis
---
flowchart RL
    constants[constants]
    keymap[keymap]
    operators_dopesheet_helper(operators.dopesheet_helper)
    operators_handle_selection(operators.handle_selection)
    operators_keyframe_moving(operators.keyframe_moving)
    overlay[overlay]
    preferences[preferences]
    utils_logger_prefs(utils.logger_prefs)
    utils_logging(utils.logging)
    utils_ui_utils(utils.ui_utils)
    operators_dopesheet_helper --> operators_handle_selection
    operators_dopesheet_helper --> operators_keyframe_moving
    operators_handle_selection --> preferences
    operators_keyframe_moving --> preferences
    overlay --> preferences
    utils_logger_prefs --> preferences
    utils_logging --> constants
    utils_logging --> keymap
    utils_logging --> operators_dopesheet_helper
    utils_logging --> operators_handle_selection
    utils_logging --> operators_keyframe_moving
    utils_logging --> overlay
    utils_logging --> preferences
    utils_logging --> utils_logger_prefs
    utils_logging --> utils_ui_utils
    utils_ui_utils --> utils_logger_prefs
